import localFont from "next/font/local";
import "./globals.css";
import NavbarPublic from "./(routes)/(public)/components/NavbarPublic";
import NavbarUser from "./(routes)/(user)/components/NavbarUser";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const user = req.headers["X-User"];
  return (
    <>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {!user && <NavbarPublic />}
          {user && <NavbarUser />}
          {}
          {children}
        </body>
      </html>
    </>
  );
}
